first attempt

diff --git a/auto/config b/auto/config
--- a/auto/config
+++ b/auto/config
@@ -1,19 +1,53 @@
-#!/bin/bash
+#!/bin/sh
 
-set -Eeux
+set -e
 
-source vars.sh
+. ./terraform.conf
 
-# TODO: Focal doesn't have a xserver HWE stack yet
-XORG_HWE="${XORG_HWE:-}"
-
-# HWE starts with y, Y or 1?
-if [ "$HWE" = "yes" ]; then
+if [ "$HWE_KERNEL" = "yes" ]; then
     KERNEL_FLAVORS="generic-hwe-${BASEVERSION}"
-    # XORG_HWE="xserver-xorg-hwe-${BASEVERSION}"
 else
     KERNEL_FLAVORS="generic"
 fi
+
+if [ "$HWE_X11" = "yes" ]; then
+    XORG_HWE="xserver-xorg-hwe-${BASEVERSION}"
+fi
+
+# lb config noauto \
+#     --architectures "$ARCH" \
+#     --mode ubuntu \
+#     --initramfs none \
+#     --distribution "$BASECODENAME" \
+#     --parent-distribution "$BASECODENAME" \
+#     --archive-areas "main restricted universe multiverse" \
+#     --parent-archive-areas "main restricted universe multiverse" \
+#     --linux-packages linux-image \
+#     --linux-flavours "$KERNEL_FLAVORS" \
+#     --bootappend-live "boot=casper maybe-ubiquity quiet splash" \
+#     --debootstrap-options="--extractor=ar --keyring=/etc/apt/trusted.gpg" \
+#     --checksums md5 \
+#     --mirror-bootstrap "$MIRROR_URL" \
+#     --parent-mirror-bootstrap "$MIRROR_URL" \
+#     --parent-mirror-chroot "$MIRROR_URL" \
+#     --mirror-chroot-security "http://security.ubuntu.com/ubuntu/" \
+#     --parent-mirror-chroot-security "http://security.ubuntu.com/ubuntu/" \
+#     --mirror-binary-security "http://security.ubuntu.com/ubuntu/" \
+#     --parent-mirror-binary-security "http://security.ubuntu.com/ubuntu/" \
+#     --mirror-binary "http://archive.ubuntu.com/ubuntu/" \
+#     --parent-mirror-binary "http://archive.ubuntu.com/ubuntu/" \
+#     --keyring-packages ubuntu-keyring \
+#     --apt-options "--yes --option Acquire::Retries=2 --option Acquire::http::Timeout=45" \
+#     --cache-packages false \
+#     --uefi-secure-boot enable \
+#     --binary-images iso-hybrid \
+#     --iso-application "$NAME" \
+#     --iso-volume "$NAME" \
+#     --firmware-binary false \
+#     --firmware-chroot false \
+#     --zsync false \
+#     --security true \
+#     "${@}"
 
 lb config noauto \
     --architectures "$ARCH" \
@@ -26,6 +60,7 @@ lb config noauto \
     --linux-packages linux-image \
     --linux-flavours "$KERNEL_FLAVORS" \
     --bootappend-live "boot=casper maybe-ubiquity quiet splash" \
+    --checksums md5 \
     --mirror-bootstrap "$MIRROR_URL" \
     --parent-mirror-bootstrap "$MIRROR_URL" \
     --parent-mirror-chroot "$MIRROR_URL" \
@@ -33,20 +68,18 @@ lb config noauto \
     --parent-mirror-chroot-security "http://security.ubuntu.com/ubuntu/" \
     --mirror-binary-security "http://security.ubuntu.com/ubuntu/" \
     --parent-mirror-binary-security "http://security.ubuntu.com/ubuntu/" \
-    --mirror-binary "mirror://mirrors.ubuntu.com/mirrors.txt" \
-    --parent-mirror-binary "mirror://mirrors.ubuntu.com/mirrors.txt" \
+    --mirror-binary "http://archive.ubuntu.com/ubuntu/" \
+    --parent-mirror-binary "http://archive.ubuntu.com/ubuntu/" \
     --keyring-packages ubuntu-keyring \
-    --apt-options "--yes --option Acquire::Retries=5 --option Acquire::http::Timeout=100" \
+    --apt-options "--yes --option Acquire::Retries=2 --option Acquire::http::Timeout=45" \
     --cache-packages false \
-    --cache-stages false \
     --binary-images iso-hybrid \
     --iso-application "$NAME" \
     --iso-volume "$NAME" \
-    --initsystem systemd \
     --firmware-binary false \
     --firmware-chroot false \
-    --syslinux-theme ubuntu-xenial \
     --zsync false \
+    --security true \
     "${@}"
 
 # replace channel and suite
@@ -55,11 +88,11 @@ sed -i "s/@BASECODENAME/$BASECODENAME/" config/archives/*.list*
 
 DATE=$(date +%Y%m%d)
 sed -i "s/@CHANNEL/$CHANNEL/" config/includes.binary/.disk/info
+# sed -i "s/@CODENAME/$CODENAME/" config/includes.binary/.disk/info
 sed -i "s/@ARCH/$ARCH/" config/includes.binary/.disk/info
 sed -i "s/@DISTRO_NAME/$NAME/" config/includes.binary/.disk/info
 sed -i "s/@VERSION/$VERSION/" config/includes.binary/.disk/info
 sed -i "s/@DATE/$DATE/" config/includes.binary/.disk/info
 
-if [ ! "x${XORG_HWE}" == "x" ] ; then
-  sed -i "s/#@XORG_HWE/$XORG_HWE/" config/package-lists/desktop.list.chroot_install
-fi
+sed -i "s/@XORG_HWE/$XORG_HWE/" config/package-lists/desktop.list.chroot_install
+sed -i "s/@KERNEL_HEADERS/linux-headers-$KERNEL_FLAVORS/" config/package-lists/desktop.list.chroot_install
